### PR TITLE
Danielr 163

### PR DESCRIPTION
**Pull request by danrossi**
The memory leak fixes. All timers needed improvements. Playlist has been change, display list management in screen has been improved. The xml in the property binder should be cleared from memory I believe other cloning utils do this also. However a better system for the property binder is storing it into a static dictionary perhaps but out of the scope for this round I think.

### CODE REVIEW

**Comment by anssip** [comment]
Thanks @danrossi , looks good. I'll check why that gitbot build failed. Will test and merge this.

**Comment by danrossi** [comment]
Might need proper testing before merging I think because of the surgery required ;) Its building here fine. A build log would be nice ?

**Comment by danrossi** [comment]
I'll do a few more final tests with the controls as it might need some things done there also not sure. Had to do reduction methods so was testing without controls loaded.

**Comment by anssip** [comment]
The build failed because gitbot could not create more S3 buckets. I deleted some and not it succeeded. Here's the adhoc site: http://flash.172f.flowplayer.me

I'll do some testing today for it.

**Comment by anssip** [comment]
The buffering animation seems to not disappear quite often. Stays on after pause and resume. Happens a lot in demo http://flash.172f.flowplayer.me/demos/configuration/playlist.html

**Comment by anssip** [comment]
En exception happens in this demo: http://flash.172f.flowplayer.me/demos/configuration/rss-playlist.html

```
TypeError: Error #1010: A term is undefined and has no properties.
    at org.flowplayer.model::Playlist/doReplace()
    at org.flowplayer.model::Playlist/addClip()
    at RSSPlaylistParser/parse()
    at PlaylistBuilder/parse()
    at PlaylistBuilder/createPlaylist()
    at org.flowplayer.config::Config/getPlaylist()
    at MethodInfo-79()
```

**Comment by anssip** [comment]
Exception in this demo: http://flash.172f.flowplayer.me/demos/configuration/instream-playlist.html

```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
    at org.flowplayer.model::Playlist/addChildClip()
    at org.flowplayer.model::Playlist/doAddClip()
    at org.flowplayer.model::Playlist/http://flowplayer.org/core/internal::setClips()
    at PlaylistBuilder/createPlaylist()
    at org.flowplayer.config::Config/getPlaylist()
    at org.flowplayer.config::Config/getLoadables()
    at org.flowplayer.view::Launcher/loadPlugins()
    at org.flowplayer.view::Launcher/initPhase2()
    at org.flowplayer.view::Launcher/callAndHandleError()
    at org.flowplayer.view::Launcher/loadPlaylistFeed()
    at org.flowplayer.view::Launcher/initPhase1()
    at org.flowplayer.view::Launcher/callAndHandleError()
    at org.flowplayer.view::Launcher/createFlashVarsConfig()
    at org.flowplayer.view::Launcher/callAndHandleError()
    at org.flowplayer.view::Launcher/onAddedToStage()
    at flash.display::DisplayObjectContainer/addChild()
    at org.flowplayer.view::Preloader/initialize()
    at org.flowplayer.view::Preloader/completeInitialize()
    at org.flowplayer.view::Preloader/onComplete()
```

**Comment by danrossi** [comment]
ok ill have a look at those. its to do with the event listener and instream clips.

**Comment by danrossi** [comment]
I made fixes to those but I have to confirm buffer indicators on the instream function I think this is an old problem perhaps nothing to do with the event changes. 

There is one other thing i've noticed with the controls. Not a big deal I think in terms of memory usage from what I can see but there is 3 timers running at the same time doing the same thing for the duration in the player, and time display and the scrubber on the controls. Perhaps if this was dispatched as a time update event from the player, the event can be binded / unbinded when needed so there is only ever one timer running for time updates ???

onTimeUpdate(function(event:PlayerEvent):void { 
  event.time // here
}

I had to disable this error dispatch on the go animation library it was showing up heaps in scout. I did some timer "improvements" on the scrubber one will get cleared but another is an anonymous function and needs extra variables to move it to an external method so had to be setup as weak for the garbage collector.

**Comment by anssip** [comment]
Merged this. There's a problem in this demo: http://flash.dev94.flowplayer.us/demos/configuration/instream-playlist.html  It does not continue after the midroll finishes.

I will test more today.

**Pull request merged**
