### PR TITLE
#27 regression caused by #550, only stop the player for live streams. ca...

### PR DESCRIPTION
**Pull request by danrossi**
...used issues when stopping between playlist items.

### CODE REVIEW

**Comment by danrossi** [comment]
any luck with these :)

**Comment by danrossi** [comment]
There is a heap more commits I've been adding to this branch.

**Comment by anssip** [comment]
Cool. I need to merge this soon :-)

**Comment by danrossi** [comment]
When you have a moment, they are fixes ;)

**Comment by danrossi** [comment]
When you have a moment there is much more to merge.

**Comment by ViliusS** [comment]
Hi anssip. Considering that current release have some high profile bugs, it would be really great to have this merged and released as 3.2.16 (or whatever) soon.

**Comment by danrossi** [comment]
Possible to get all these in, there is a bit of a backlog now :) thanks !

**Comment by danrossi** [comment]
I'm being slammed with HLS plugin requests which needs some code merged. Any ideas when just that part can be done , i dont know how to hand pick merges.

**Pull request merged**
