### PR TITLE
- #70 fixes for live streams with httpstreaming

### PR DESCRIPTION
**Pull request by danrossi**
Lets try this again

### CODE REVIEW

**Comment by danrossi** [comment]
have got confirmation the httpstreaming switching updates are working, so please proceed with this long list thanks. It would be good to be able to merge the deletion of the hls plugin from the master rep to avoid confusion.

**Comment by rdkls** [comment]
These changes are awesome, well done @danrossi.
@anssip i recommend getting them in asap - without them, the bandwidth selection is very basic, and often gives much worse quality stream than it should.
With them, our videos are looking awesome.

**Comment by danrossi** [comment]
There is probably alot of conflicts now as the commits have been incrementing, please just use the build i sent to you before and it should be ok to use. I'm not too surely when they will be officially released, thanks !

**Comment by rdkls** [comment]
Will do, thanks again

**Pull request merged**
